system:
  ip: ""
  port: "8080"
  gin_mode: release
  env: dev
log:
  app: blogx_server
  dir: logs
db:
  - user: root
    password: 123456
    host: 192.168.168.128
    port: 3306
    db: blogx
    debug: false
    source: mysql
  - user: root
    password: 123456
    host: 192.168.168.128
    port: 3307
    db: blogx
    debug: false
    source: mysql
es:
  addr: 192.168.168.128:9200
  is_https:
  username:
  password:
river:
  enable: true
  server_id: 1001
  flavor: mysql
  data_dir: ./var
  source:
    - schema: blogx
      tables:
      - article_models
  rule:
    - schema: blogx
      table: article_models
      index: article_index
      type: _doc
      field:
        tag_list: tag_list,list
  bulk_size: 128
jwt:
  expire: 24
  secret: xxx
  issuer: hjy
redis:
  addr: 127.0.0.1:6379
  password: "1234"
  db: 0
site:
  siteInfo:
    title: 小演博客1
    logo: ""
    beian: ""
    mode: 1
  project:
    title: 演演知道
    icon: /xxx.png
    webPath: uploads/index.html
  seo:
    keywords: "1"
    description: "1"
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailLogin: true
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: true
    commentLine: 0
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 3027373171@qq.com
  authCode: xfslyhcacmgndgah
  sendNickname: yanyan
  ssl: true
  tls: false
qq:
  appID: "1234"
  appKey: ""
  redirect: http://xxxxxx
qiNiu:
  enable: true
  accessKey: OysF3Hj6R39-LCDZS9cyy2vRgXEl4e1-1Pv5w-EI
  secretKey: 2n78I3G_5AlldZWgM8nE7U_rfsi5RjrC0Bz9ZT1N
  bucket: pity
  uri: http://st7hmu9be.hn-bkt.clouddn.com
  region: z2
  prefix: blogx
  size: 3
  expiry: 60
ai:
  enable: false
  secretKey: ddasjhdshfdsnfdsjfioeos384u3289rh89r8932r893
  nickname: 小演
  avatar: /xxx/xxx
  abstract: ""
upload:
  size: 3
  whiteList:
  - jpg
  - jpeg
  - png
  - webp
  - gif
  uploadDir: images001
